// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportApi.DbReporsitory;

namespace SportApi.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20221209131011_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SportApi.DbReporsitory.Models.GoodsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ball1",
                            Price = 100,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ball2",
                            Price = 150,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ball3",
                            Price = 200,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sneakers1",
                            Price = 90,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sneakers",
                            Price = 90,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sneakers1",
                            Price = 90,
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
